### PR TITLE
Steering transition smooth OP->Human->OP

### PR DESCRIPTION
**Pull request by bitshop**
I'd like others to test this transition, I want to optimize a bit the code after others agree they like this transition. The warnings for taking over are still there but slightly mismatched.. It's smooth enough sometimes that you may not be sure if it's driving or not after you take over..

### CODE REVIEW

**Comment by jeankalud** [comment]
Will test tomorrow, thanks!

EDIT: testing now...

**Comment by DavidWAbrahams** [comment]
Cool feature!

Small style nit: in python code, don't add parentheses around 'if' statements unless it makes a complicated line easier to read. for example
"if (angle > 70):"
should just be
"if angle > 70:"

**Comment by bitshop** [comment]
Improved version coming..

**Comment by bitshop** [comment]
Oops, new commits show up, I shouldn't close this.

**Comment by bitshop** [comment]
Closing to open new one to be clearer for those testing..

**Pull request closed without merging**
