### PR TITLE
Avoid merge conflics with panda master / add alt function for GMLAN

### PR DESCRIPTION
**Pull request by appleguru**
Assumes comma merges in PR 128: https://github.com/commaai/panda/pull/128

Please test!

### CODE REVIEW

**Comment by jeankalud** [comment]
David. can you please test this out. Need to check if giraffe switch from green to orange/yellow, once it sets tesla safety. Best way to test is, load this, flash panda. Remove panda (or whole giraffe+panda), add it back. After a couple seconds it will switch from green to orange/yellow.  Then check if everything looks normal (enable / disable OP).

It kind of need to be done soon, need feedback before merging into comma's Panda code for all.

Need a RevA Giraffe with the GMLAN gpio connected, like on yours. Let me know if you are unable to test.

My wife has the Model S today and tomorrow... :(

**Comment by DavidWAbrahams** [comment]
I'll perform the manual test in the next 1 hour.

**Comment by DavidWAbrahams** [comment]
Initial manual test passes (load this, flash panda. Remove panda (or whole giraffe+panda), add it back. After a couple seconds it will switch from green to orange/yellow.)

Going for a quick drive now to confirm.

**Comment by DavidWAbrahams** [comment]
No glaring issues in a 5 minute drive, pull request accepted to tesla_devel branch.

**Comment by jeankalud** [comment]
Thank you so much!

**Pull request merged**
