### PR TITLE
Add seatbelt buckled instead of (or with) driver's presence detection to safety checks

### PR DESCRIPTION
**Pull request by BobbyBleacher**
Stops OP from disabling itself when it doesn't sense you in the seat

### CODE REVIEW

**Comment by jeankalud** [comment]
We need to find seatbelt instead. I understand your point but it’s basic safety, if driver is not detected OP shouldn’t be active. Let’s find a solution instead that simply disable that safety check

**Comment by bitshop** [comment]
@BobbyBleacher Did we find seat belt by chance? I'd love to get that in there and have our main branch working for you..

**Comment by jeankalud** [comment]
I personally didn't find seatbelt... Must be on body CAN I guess... argh..

**Comment by BobbyBleacher** [comment]
Haven't had my car for a week... Supposed to be back Wednesday. I'll start digging through Body CAN when it comes back.

**Comment by BobbyBleacher** [comment]
Been searching all through can messages in dev mode, buckling/unbuckling the seat belt with no luck so far.

**Comment by BobbyBleacher** [comment]
Found it in ETH:SDM1, SDM_buckleDriverStatus, but zax says it's not in the DBC.

**Comment by jeankalud** [comment]
Not on the DBC because its on Ethernet bus. Must be somewhere on either chassis or body canbus... Then forwarded on Ethernet

**Comment by BobbyBleacher** [comment]
I'll keep looking on my way to work

**Comment by jeankalud** [comment]
@zax123 says: Little birdie has helped find the seatbelt buckle status and turns out it is in chassis CAN after all which is good news for us.  I'm still so confused as to how to branch stuff in git, so here are the changes, could someone incorporate them? :slightly_smiling_face: 

First, these three lines need to be added to the DBC file.  The BO_ section is in alphabetical order by message name:
BO_ 513 SDM1: 5 SDM
 SG_ SDM_bucklePassengerStatus : 3|2@0+ (1,0) [0|3] "" OCS,GTW
 SG_ SDM_buckleDriverStatus : 5|2@0+ (1,0) [0|3] "" OCS,GTW

And then in carstate.py, add this line to the end of the list of signals:
      `("SDM1", "SDM_buckleDriverStatus", 0),`

And then finally, change the line setting the state variable of self.seatbelt to this:
    `self.seatbelt = cp.vl["SDM1"]["SDM_buckleDriverStatus"]`

That value goes to 1 when seatbelt is buckled and 0 when seatbelt is unbuckled.  Easy peasy!
For absolute safety (seatbelt buckled and driver present check) that last line could actually be:
`self.seatbelt = cp.vl["SDM1"]["SDM_buckleDriverStatus"] & cp.vl["GTW_status"]['GTW_driverPresent']`
which would make sure both are set...

**Comment by bitshop** [comment]
I changed the base to tesla_devel instead of the main branch that this will go into.

**Comment by bitshop** [comment]
Doing a manual merge of this since the text comments exist and I can't write to this repo it's sourced from.  Will test in my car before merging.

**Comment by bitshop** [comment]
Merged in https://github.com/jeankalud/openpilot/tree/BobbyBleacher-patch-3

**Comment by bitshop** [comment]
Closing this one out since it will be a new pull request with the commented changes.   See https://github.com/jeankalud/openpilot/pull/30

**Pull request closed without merging**
